### PR TITLE
Fb change database

### PR DESCRIPTION
**Pull request by SFulpius**
This fixes issue #49.

The legacy DatabaseConnection class is now deleted. All the usage of the class are replaced by Database. Database is easier to use as the listener directly return values and not DataSnapshots. It is also easier to test.

### CODE REVIEW

**Comment by robinmamie** [comment]
The tests crashed on Travis because it uses API **22**, whereas locally we would test on API **25**. The latter handles layouts differently than the former, so it resulted in obscure crashes.

**Comment by SFulpius** [comment]
Actually the tests were not failing because of the layout, nor because of the api. The tests try to access the user using the static method. We are not logged in the app on Travis, so it returned null and caused NullPointerException. I changed with a new emulator were I was not logged in and I got the same crashes.

**Comment by robinmamie** [comment]
> Actually the tests were not failing because of the layout, nor because of the api. The tests try to access the user using the static method. We are not logged in the app on Travis, so it returned null and caused NullPointerException. I changed with a new emulator were I was not logged in and I got the same crashes.

Ok I see. So do you know why the tests passed locally but not on Travis? Or they originally also didn't pass locally?

**Comment by SFulpius** [comment]
I was logged in with my account on the emulator. On Travis nobody was logged in, so the user was null.

**Pull request merged**
