### PR TITLE
Add the remove method to the database

### PR DESCRIPTION
**Pull request by SFulpius**
This close issue #65 .

### CODE REVIEW

**Comment by dingepfl** [comment]
I resolved the conflicts (in the file ListOfferAdapter.java) that were created with the merge of the commit d13f18edfcbefeb56a5a34d653c5ecfe63b5a034 to master

**Comment by SFulpius** [comment]
> I resolved the conflicts (in the file ListOfferAdapter.java) that were created with the merge of the commit [d13f18e](https://github.com/SwengGolfTeam/Sweng_Golf/commit/d13f18edfcbefeb56a5a34d653c5ecfe63b5a034) to master

Thank you.

**Comment by SFulpius** [comment]
> I resolved the conflicts (in the file ListOfferAdapter.java) that were created with the merge of the commit [d13f18e](https://github.com/SwengGolfTeam/Sweng_Golf/commit/d13f18edfcbefeb56a5a34d653c5ecfe63b5a034) to master

Thank you.

**Comment by SFulpius** [comment]
> I resolved the conflicts (in the file ListOfferAdapter.java) that were created with the merge of the commit [d13f18e](https://github.com/SwengGolfTeam/Sweng_Golf/commit/d13f18edfcbefeb56a5a34d653c5ecfe63b5a034) to master

Thank you.

**Pull request merged**
